SUPPORTED_VOICES = {
    'Female-AnaNeural': 'en-US-AnaNeural',
    'Female-AriaNeural': 'en-US-AriaNeural',
    'Male-ChristopherNeural': 'en-US-ChristopherNeural',
    'Male-EricNeural': 'en-US-EricNeural',
    'Male-GuyNeural': 'en-US-GuyNeural',
    'Female-JennyNeural': 'en-US-JennyNeural',
    'Female-MichelleNeural': 'en-US-MichelleNeural',
    'Male-RogerNeural': 'en-US-RogerNeural',
    'Male-SteffanNeural': 'en-US-SteffanNeural',
    'Female-XiaoxiaoNeural': 'zh-CN-XiaoxiaoNeural',
    'Female-XiaoyiNeural': 'zh-CN-XiaoyiNeural',
    'Male-YunjianNeural': 'zh-CN-YunjianNeural',
    'Male-YunxiNeural': 'zh-CN-YunxiNeural',
    'Male-YunxiaNeural': 'zh-CN-YunxiaNeural',
    'Male-YunyangNeural': 'zh-CN-YunyangNeural',
}
